### ISSUE TITLE
Categories for products, pagination

### ISSUE THREAD

**Issue by ExploreLearnMake** [rsc-media/shoppingCart#1]
I would like to request a new feature of the shopping cart. The ability to separate the products by category so groups of products could be displayed across multiple pages.

I'm thinking we can add a category name to the product objects in the JSON file. Then have a way to filter/display only a desired category on a page. Maybe have an attribute on the HTML element wrapper for the products so it can easily be changed by students. This would allow them to use the various categories they already set up within the current lesson assignments and only display a small subset of the products on the different pages.

**Comment by jasonreiche** [comment]
An attribute on the HTML or BODY tag would take care of this nicely.  2 other ideas I had:
* Use a META tag such as `<meta name='category' content='Bath Bombs'>`
  * There isn't an 'official' product tag as defined by W3C or Google, as far as I'm aware.
* Use the filename of the page to identify the category.  I already use this to identify the Checkout page.
Thoughts?

**Comment by ExploreLearnMake** [comment]
I think the META tag would be the best option as it would fall under the principle of page metadata and would follow best practices because of that.

**Comment by jasonreiche** [comment]
The Category Feature has been built out and deployed.  It is using the meta tag discuss above.  With this work?
[Commit](https://github.com/rsc-media/shoppingCart/commit/dd7ae75d5dad671ca67a11c2c2306f64aa93e603) - [Page](https://rsc-media.github.io/shoppingCart/index.html)

**Comment by ExploreLearnMake** [comment]
It looks great. There is just one little quirk that I noticed. I added something from the square page, then added something from the die cut page. The square page acted fine and was added to the cart. But the die cut did not. It did not appear after I clicked the add to cart button, at first. Only after I clicked it a second time did it appear in the cart, but with 2 in the quantity column. Adding subsequent items seemed to work. 

Another thing, probably related, when I switch between pages, some of the items in the cart disappear. If I add a new item, or change a quantity in the cart, the "missing" items reappear correctly. Playing around further, it just seems those items from the last page (Square) go missing. Even when I go to that page. 

So it is keeping track of things added to the cart, including the total cost, but something occurs during the displaying of the items in the cart.

**Comment by jasonreiche** [comment]
Strange.  I was not able to replicate the reported behavior.  I did find and resolve a couple of CSS issues.  What browser were you seeing this behavior in?  I've tried on Chrome 87 and Firefox 85 both on the work and home machines.

**Comment by ExploreLearnMake** [comment]
I still get the issue with Edge 89 (Dev), Firefox (85). It seems that if it has a lot of items in the cart the issue appears. Also, I noticed the sort order in the cart will change sometimes when switching pages. Not sure why that happens or how it sorts the cart.

Here is GIF of what I did so you can see. This is in FF.
![2021-01-26_12-26-21](https://user-images.githubusercontent.com/25446111/105894937-17ae4580-5fd2-11eb-895a-f6b359ee878c.gif)

**Comment by jasonreiche** [comment]
I have pushed a few commits that I think will address the issue.  2 directly affect sorting and the other I think was the bug causing this issue.  Please refresh, empty the cart, and test again.

**Comment by jasonreiche** [comment]
You had mentioned pagination in the issue subject line.  Do you feel we need to have a pagination feature beyond what we have done so far?

**Comment by ExploreLearnMake** [comment]
It seems to be working now. Thank you. 

Regarding pagination - when I used that I meant more allowing items to be displayed across multiple HTML pages rather than a page 1, 2, etc. navigation system or only showing a certain number of items on a page that you might see within a table of data. I think what we have is good. I do not expect to have more than a handful of items per page, so we don't need to figure out how to limit the number of displayed items on the page. I think we can close this issue. Thanks again for getting this done.
